### ISSUE TITLE
Remove npm update hack for Node.js. 14 on Windows

### ISSUE THREAD

**Issue by ybiquitous** [stylelint/.github#17]
Node.js 14 will reach EOL on 2023-04-30. Then, we can remove the following hack:

https://github.com/stylelint/.github/blob/d36a2eb3a3684d68d7ea293c49387a46f1fa9f17/.github/workflows/test.yml#L44-L47

Ref:
- https://github.com/npm/cli/issues/4341
- https://github.com/stylelint/.github/pull/15#discussion_r1024614866
- https://github.com/nodejs/release#release-schedule

**Comment by ybiquitous** [comment]
For reference. We can see the usage of `engines.node` in `package.json` in this organization:
https://github.com/search?q=org%3Astylelint+%22%5C%22node%5C%22%3A%22+path%3A**%2Fpackage.json&type=code

**Comment by ybiquitous** [comment]
Another search for the usage of `.github/workflows/test.yml` in this organization:
https://github.com/search?q=org%3Astylelint+%22stylelint%2F.github%2F.github%2Fworkflows%2Ftest.yml%22+language%3AYAML&type=code

**Comment by jeddy3** [comment]
Judging from those searches, am I right to think we can remove this hack?

**Comment by ybiquitous** [comment]
Yes, I think so. 👍🏼
