### ISSUE TITLE
NPM 11 drops support for Node 18

### ISSUE THREAD

**Issue by jeddy3** [stylelint/.github#39]
### What steps are needed to reproduce the bug?

Failing builds at stylelint/stylelint:

```
Run npm install --global npm@latest
npm error code EBADENGINE
npm error engine Unsupported engine
npm error engine Not compatible with your version of node/npm: npm@11.0.0
npm error notsup Not compatible with your version of node/npm: npm@11.0.0
npm error notsup Required: {"node":"^20.17.0 || >=22.9.0"}
npm error notsup Actual:   {"npm":"10.8.2","node":"v18.20.[5](https://github.com/stylelint/stylelint/actions/runs/12373968339/job/34535444731?pr=8207#step:7:6)"}
npm error A complete log of this run can be found in: /Users/runner/.npm/_logs/2024-12-1[7](https://github.com/stylelint/stylelint/actions/runs/12373968339/job/34535444731?pr=8207#step:7:8)T13_25_59_003Z-debug-0.log
Error: Process completed with exit code 1.
```

https://github.com/stylelint/stylelint/actions/runs/12373968339/job/34535444731?pr=8207

### What did you expect to happen?

For Node 18 to install NPM 10

Looks like we need a new conditional:

https://github.com/stylelint/.github/blob/a872a618333ba52bd2d09857cfe86ad21250464e/.github/workflows/test.yml#L104-L115

### What actually happened?

Build failed.

**Comment by ybiquitous** [comment]
Oh, npm@11 has been released recently. I'll fix it 👍🏼 
https://github.com/npm/cli/releases/tag/v11.0.0
